### ISSUE TITLE
Intermittent erroring output, no discernible cause, no SoS functionality

### ISSUE THREAD

**Issue by jaxx050** [BrianOstrander/pz-save-our-station#6]
Basically every time (I think) the radio updates hourly, it instead spits an error and nothing happens, and SoS doesn't seem to be really...doing anything. I haven't been to a station yet but that's never been an issue before, I have the full output log put on a file share since it's like 285,000 lines and too large for most any text paste sites: https://ufile.io/gfby22e9

**Comment by YoshiWoof22** [comment]
Hey there @jaxx050, thanks for taking the time to get the Log and file a report here ^^

Having checked through the log, the issue looks to be very much identical to the previously-reported issue #5.

Thus, as I have initially stated in my first Steam reply, I again suspect some form of file corruption to be at play.
Please try [verifying your Project Zomboid's Game File Integrity](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) and see if that does anything to resolve your issue.

If that doesn't do it, please get back to me here - I'll likely need your save file so I can debug it locally.

**Comment by jaxx050** [comment]
That was the first thing I had done and it seemed to have worked but almost immediately was broken again, so here's my save file, it has quite a few mods to it and I don't know of a convenient way to add those to a list (because steam workshop is a nightmare): https://we.tl/t-6IRfLVr2PC

**Comment by YoshiWoof22** [comment]
Hey @jaxx050 , sorry for the delayed reply - I was a bit busy over the Weekend.

But, in some good news, I just checked your save and I'm pretty certain I found your issue. I didn't even have to load the save to notice, surprisingly.

It seems like you don't have the "Save Our Station! Knox Country" Map active in your save (see attached Images below).
This explains the issue: Without that map enabled, none of the weather stations actually generate, which causes the actual Save Our Station script to throw an error as it tries to access stations that don't exist.

---
**Your "Survive"-Save:**
![image](https://github.com/BrianOstrander/pz-save-our-station/assets/31738147/386d525f-636b-4374-b679-8b53c03273f4)
**Proper example, using just SoS and Mod Manager:**
![image](https://github.com/BrianOstrander/pz-save-our-station/assets/31738147/73f6316c-1d02-40da-aba2-f57d31024cc2)

---
I'm afraid this slipped by me when checking your log initially. Having checked again after noticing the map missing in your save, I also noticed the map wasn't showing up in the log either, which confirms the issue - **make sure you have the "Knox Country" map active along with the "Core"**.

That being said, I see now that Map-loading related errors are a more common issue than I expected.

I'll see if there's some way to implement a message to inform end users of an improper/faulty SoS Setup, as opposed to these cryptic errors. In addition, I'll be working on a proper Troubleshooting page - most likely going to be on the GitHub here, as people don't check Steam Discussions thoroughly enough.

Hoping this resolves your issue now, and I hope to hear back from you with positive news ^^

**Comment by jaxx050** [comment]
i ...... 
jesus christ. i had it loaded on my main menu mod preset but i guess making the save didn't keep it on properly. well, at least i know why.
e: while my errors haven't ceased, i would imagine that's mostly due to the fact that though i haven't actively visited the stations, they did get map loaded for me so they aren't actually *there* for core to call on them. is there any way to surgically paste those map sections in post-generation? if not, the error is fixed, and it existed between user and keyboard 🥲

**Comment by YoshiWoof22** [comment]
@jaxx050 I was going to reply yesterday morning and close the issue before you made that edit, but forgot to actually send it... so good thing that happened.

Don't worry about how the issue occurred - stuff like that can happen. Happened to me before, too.
But yeah, the maps need to physically exist for it to work properly I'm afraid.

RE: Surgically inserting the map cells after world creation...
I've heard its possible, and it looks like there's some guides for doing so, but generally we'd advise against it due to the fact it might cause other, harder-to-diagnose issues (never tried it with SoS).

I personally would suggest a new world, as sad as that is (Sorry!).
That being said, you're free to try splicing, but that'll be "out of warranty" on my emd /shrug

If this resolves your issue for good (try a new world to confirm), I'd just appreciate a quick reply so I can know whether to mark this as resolved ^^
Cheers!

**Comment by jaxx050** [comment]
To my knowledge based on starting a new map, yeah that seemed to be the issue, and I would like to attempt splicing if at all possible. Do you happen to know the SoS map cells' numbers for map tile deletion to "regenerate" them in-situ?

**Comment by YoshiWoof22** [comment]
@jaxx050 Happy to hear its resolved. Good luck with the splicing!

The map cell numbers should be as follows, per the [Mod/Map Compatibility List pinned over in the Steam Discussions](https://steamcommunity.com/workshop/filedetails/discussion/2398274461/3785877016600078243/)
```
21x39
24x18
25x38
34x34
35x24
```
I don't recall which number matches to which of the 5 stations of the top of my head, but I hope this helps.
I'll be marking this as resolved in the meantime, but keeping the issue open.

Feel free to report back with your results of the splice once its concluded (and close the issue once you've finished) - would be good to know if its possible, and what steps you are taking/have taken, for documentation purposes.

>>> Quick edit: Will be adding/trailing our new issue label system here, so don't mind the sudden change!

**Comment by jaxx050** [comment]
so uh ... i've been looking at this off and on to try and test it by deleting those specific map cells to try it, but looking at the map data, it just doesn't make sense to me? the steam guide (at here https://steamcommunity.com/workshop/filedetails/discussion/2536865912/3051734893991241620/ ) mentions using the coordinates of the areas you're in, but 21*39 for example would not seem to correspond to any map files using this structure it uses for formatting: https://i.gyazo.com/986134e0a751bfa61ad54067a172c330.png
nor would any of the others, seemingly. i believe the ONLY one i would have generated is the secret military tower (if the chunk generation radius is reasonable like 3-4 chunks), since i've been relatively relegated to the southwest portion of the map. i know this is out of your purview but any help would be appreciated if it can be offered :') if for example you know the exact coordinates of the military tower, since i think that's what the mod is trying to "communicate" with

**Comment by YoshiWoof22** [comment]
@jaxx050 Apologies for the delayed reply - I kinda assumed this ticket went stale after my last reply.

The **coordinates** you and the tutorial mention are not the same as the **map cells** (if you played Minecraft before, think of cells as chunks).

I don't know the coordinates you need off the top of my head i'm afraid, **BUT** I think I got a method for you that might work:
1. Use the map cells I mentioned and find the actual in-game location via https://map.projectzomboid.com/ (check in the "Map Coordinates" menu on the left). You can find the coordinates directly this way too, but its annoying due to it being a lot of files, so I suggest you proceed with Step 2:
2. Use debug mode to teleport to every location and "generate" the area around every station (or at least, the area where they WOULD be). This will be necessary for Step 4.
3. Make sure your mod/map load order is correct now.
4. Use https://grabofus.github.io/zomboid-chunk-cleaner/ to delete/reset those specific regions of your savegame, allowing the stations to generate.
5. Profit? I hope?

Im hoping this helps you out. Please keep me posted, especially if it works, so that I can close this off :)

**Comment by jaxx050** [comment]
good news! it doesn't help me! /s
ok but in actuality, regenerating those cells did *not* restore functionality to the script calls of SoS even after the stations themselves existed, so i'm gonna mark this as closed and you can know that you have to tell people to entirely regenerate maps lol.
